// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnG1CErCYmHnGoGKWMRy9kJb4J-PdPi0',
    appId: '1:259920701334:web:416403b25c2a67e45b5fb7',
    messagingSenderId: '259920701334',
    projectId: 'expenses-tracker-e7d05',
    authDomain: 'expenses-tracker-e7d05.firebaseapp.com',
    storageBucket: 'expenses-tracker-e7d05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_P8gA-_wSt383Qh7B6zrhAnHTs8wnsY',
    appId: '1:259920701334:android:686950cddc2e89eb5b5fb7',
    messagingSenderId: '259920701334',
    projectId: 'expenses-tracker-e7d05',
    storageBucket: 'expenses-tracker-e7d05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADpuwhclBluDdNftfQoLsKMpv-k5lFbaw',
    appId: '1:259920701334:ios:164599f9294e8cd75b5fb7',
    messagingSenderId: '259920701334',
    projectId: 'expenses-tracker-e7d05',
    storageBucket: 'expenses-tracker-e7d05.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADpuwhclBluDdNftfQoLsKMpv-k5lFbaw',
    appId: '1:259920701334:ios:164599f9294e8cd75b5fb7',
    messagingSenderId: '259920701334',
    projectId: 'expenses-tracker-e7d05',
    storageBucket: 'expenses-tracker-e7d05.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnG1CErCYmHnGoGKWMRy9kJb4J-PdPi0',
    appId: '1:259920701334:web:4a8a6962763e128d5b5fb7',
    messagingSenderId: '259920701334',
    projectId: 'expenses-tracker-e7d05',
    authDomain: 'expenses-tracker-e7d05.firebaseapp.com',
    storageBucket: 'expenses-tracker-e7d05.firebasestorage.app',
  );
}
